- name: Deploy Frontend for ${{ github.ref_name }}
        if: ${{ env.FRONTEND_NAME != '' }}
        run: |
          cd frontend/
          echo "${{ secrets.FRONTEND_ENV }}" > .env.prod
          pnpm install --no-frozen-lockfile
          curl -s -X POST "https://api.cloudflare.com/client/v4/accounts/$CLOUDFLARE_ACCOUNT_ID/pages/projects" \
            -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"name\":\"$FRONTEND_NAME\",\"production_branch\":\"production\"}" || true
          export frontend_branch="${{ secrets.FRONTEND_BRANCH }}"
          if [ -n "$frontend_branch" ]; then
            echo "Deploying branch $frontend_branch"
            pnpm run deploy:actions --project-name=$FRONTEND_NAME --branch $frontend_branch
          else
            echo "Deploying branch production"
            pnpm run deploy --project-name=$FRONTEND_NAME
          fi
          echo "Deployed for tag ${{ github.ref_name }}"
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          FRONTEND_NAME: ${{ secrets.FRONTEND_NAME }}
